<?php $random = mt_rand(1, 5); ?>
<?php if($this->getId() == '13'): // Kuul ?>
    <div class="block">
        <div class="block-content" style="padding: 0">
            <iframe style="width: 100%; border: 0;" src="//www.youtube.com/embed/l7wpj1sgXlI"  allowfullscreen></iframe>
        </div>
    </div>
    <?php $random = false; ?>
<?php endif ?>
<?php if($this->getId() == '16'): // Kiss ?>
    <div class="block">
        <div class="block-content" style="padding: 0">
            <iframe  style="width: 100%; border: 0;" src="//www.youtube.com/embed/VuUdpwPnQ5U?list=UUXiZjq_kllhXPUCE2GLODnw"  allowfullscreen></iframe>
        </div>
    </div>
    <?php $random = false; ?>
<?php endif ?>

<?php if($random == 1): ?>
    <div class="block">
        <div class="block-content" style="padding: 0">
            <iframe  style="width: 100%; border: 0;" src="//www.youtube.com/embed/EIkfl2RimM8"  allowfullscreen></iframe>
        </div>
    </div>
<?php endif ?>
<?php if($random == 2): ?>
    <div class="block">
        <div class="block-content" style="padding: 0">
            <iframe  style="width: 100%; border: 0;" src="//www.youtube.com/embed/-n1Dbuv1e4E" allowfullscreen></iframe>
        </div>
    </div>
<?php endif ?>
<?php if($random == 3): ?>
    <div class="block">
        <div class="block-content" style="padding: 0">
            <iframe  style="width: 100%; border: 0;" src="//www.youtube.com/embed/BsnFrT6MDNk?list=UUPnBJfTfTx_Zg9NvvKwH01Q"  allowfullscreen></iframe>
        </div>
    </div>
<?php endif ?>
<?php if($random == 4): ?>
    <div class="block">
        <div class="block-content" style="padding: 0">
            <iframe  style="width: 100%; border: 0;" src="//www.youtube.com/embed/Ho1eqp2BNtM?list=UUPnBJfTfTx_Zg9NvvKwH01Q"  allowfullscreen></iframe>
        </div>
    </div>
<?php endif ?>
<?php if($random == 5): ?>
    <div class="block">
        <div class="block-content" style="padding: 0">
            <iframe  style="width: 100%; border: 0;" src="//www.youtube.com/embed/9wJGQEgtmlY?list=UUPnBJfTfTx_Zg9NvvKwH01Q" allowfullscreen></iframe>
        </div>
    </div>
<?php endif ?>